printWidth: 200
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: "as-needed"
trailingComma: "es5"
bracketSpacing: false
bracketSameLine: true
arrowParens: "always"
requirePragma: false
insertPragma: false
htmlWhitespaceSensitivity: "ignore"
vueIndentScriptAndStyle: false
endOfLine: "lf"
embeddedLanguageFormatting: "auto"
singleAttributePerLine: false
